### PR TITLE
Add rails app into docker-compose for easy developer setup

### PR DESCRIPTION
**Pull request by seanfisher**
This PR allows a developer to use docker to quickly stand up a dev environment upon cloning the repo. It also makes the Postgres database persist across container restarts. Opening for feedback.

## Steps to run dev environment:

Software needed
- Docker
- ??

On first pull
- `$ docker-compose build`
- `$ docker-compose run web bundle exec rake db:create` -- creates database
- `$ docker-compose run web bundle exec rake db:setup` -- loads schema and seed data

Every time
- `$ docker-compose up`

To tear down
- `$ docker-compose down`

To tear down including the volumes (database)
- `$ docker-compose down -v`

Visit the site at `localhost:3000`.

`docker-compose build` will need to be re-run if the Gemfile, Gemfile.lock, or Dockerfile changes.

## Notes

Since the working directory is mounted as a volume into the container, any changes made to the application code will be immediately live in the dockerized app, but from what I've read the container could also be used for CI/CD because the current version of the code is copied into the container at container build time.

I experienced an issue where when a container stopped ungracefully it would leave behind a `.pid` file. The most elegant solution I found was to just run a script every time the container started deleting the `.pid` file if it exists.

I'd like it if somebody could test pulling this down on their machine and running it, just to verify it doesn't only work on my machine and that I didn't miss anything. If it works well we might consider adding it to the contributing file.

## Questions

Is the `docker-compose` used by any build tool or Heroku? If so, this may mess with that and need to be adjusted.

### CODE REVIEW

**Comment by seanfisher** [comment]
I need some input before merging this. We have at least two options for database connection if we want to pursue this:

1. Change the `host` in `database.yml` for the `development` environment to `postgres` instead of localhost. Anybody who's running the code outside of docker will need to add `postgres` to their hosts file
1. Add a new `docker` environment that inherit from `development` and changes `host` to `postgres`. This involves a few more changes - adding some config to `secrets.yml`, `sidekiq.yml`, etc. Then the docker compose file will set the RAILS_ENV to `docker` and away it goes.

I initially did the second because we didn't have the username/password set for `development` in `database.yml`, but after the code change earlier today where the host/username/password were set I removed the docker environment but just ran into that little snag on the host name. Let me know your thoughts on these or if there's another option you can think of.

**Comment by seanfisher** [comment]
@tsanders Thanks for switching it to staging.

I went ahead and switched to option 2 and added the new docker environment. It inherits from development settings in all cases except for switches the host name to `postgres` so it will connect to the docker Postgres server.

This should be working and ready for somebody to test now.

**Comment by tsanders** [comment]
Reviewing now

**Comment by tsanders** [comment]
@seanfisher Everything looks great!  This will be a huge help for onboarding devs with minimal setup.  Could you update the [CONTRIBUTING.md](https://github.com/CrisisCleanup/crisiscleanup/blob/master/CONTRIBUTING.md) with the setup and deployment steps you listed above for the `docker` environment?

Could we also add `--rm` to the `docker-compose run` commands to remove the container after the run (a dev would end up with a lot of dangling containers if they run those commands multiple times.) - i.e. `docker-compose run --rm web bundle exec rake db:create` and `docker-compose run --rm web bundle exec rake db:setup`.  We could also simplify to `docker-compose run --rm web bundle exec rake db:setup` because it already includes includes `db:create`.

**Comment by seanfisher** [comment]
Thanks - great ideas. I've opened #357 for the updates.

**Pull request merged**
